name: JAR build
on: [push, pull_request]
jobs:
  jar-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Maven cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Maven build
        run: mvn clean compile package
      - uses: actions/upload-artifact@v2
        with:
          name: ari.jar
          path: ./target/ari*.jar
